import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import ProfileCard from '../components/ProfileCard';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{ 'Sant\'s Portifoly' }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProfileCard />

      <main className={styles.main}>

        <h1 className={styles.title}>
          Bem Vindo(a)!
          <span>
            <b>Obrigado pela <br/>visita, <br/>volte sempre!</b>
          </span>
        </h1>

        <nav className={styles.nav}>
          <Link href="/projects">
            <h2 className={styles.card}>Projetos</h2>
          </Link>

          <Link href="/skills">
            <h2 className={styles.card}>Habilidades</h2>
          </Link>

          <Link href="/networking">
            <h2 className={styles.card}>Networking</h2>
          </Link>

          <Link href="/testimonials">
            <h2 className={styles.card}>Depoimentos</h2>
          </Link>
        </nav>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com/" target="_blank" rel="noopener noreferrer">
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
