import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono as GeistMono } from 'next/font/google';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { ToastProvider } from '@/components/ui/toast';
import { AuthProvider } from '@/lib/providers/auth-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = GeistMono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Gss Digit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-screen`}>
        <ToastProvider>
          <AuthProvider>
            <Header />

            {children}

            <Footer />
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
