import Head from 'next/head';

import ProfileCard from '../components/ProfileCard';
import Image from 'next/image';
import HeaderNav from '../components/HeaderNav';
import ProjectPost from '../components/ProjectPost';
import ProjData from '../PROJECTS_DATA';

const Home = () => {
  return (
    <div className="container">
      <Head>
        <title>{'Sant\'s Portifoly'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProfileCard />

      <HeaderNav />

      <main>
        <section className='projects'>
          <h5>Projetos:</h5>
          {ProjData.map((proj, ind) => (
            <ProjectPost key={`projct${ind}`} {...proj} />
          ))}
        </section>
      </main>

      <footer className="footer">
        <a href="https://vercel.com/" target="_blank" rel="noopener noreferrer">
          Powered by
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
