const male = {
  subs: [
    'Gato',
    'Cachorro',
    'Boleto',
    'Programador',
    'Café',
    'Bug',
    'Tatu',
    'Pão de Queijo',
    'Vira-lata',
    'Malandro',
    'Gigante',
    'Cavaco',
    'Pandeiro',
    'Jedi',
    'Viajante',
    'Astronauta',
    'Mago',
    'Robô',
    'Samurai',
    'Código',
    'Fiat Uno',
    'Observador',
    'Guitarrista',
    'Rato',
    'Capuccino',
  ],
  ads: [
    'Bagunceiro',
    'Misterioso',
    'Cansado',
    'Pagodeiro',
    'Baiano',
    'Carioca',
    'Paulista',
    'Quebrado',
    'Supremo',
    'Lendário',
    'Aleatório',
    'Sonhador',
    'Faminto',
    'Curioso',
    'Veloz',
    'Zen',
    'Hacker',
    'Invisível',
    'Divertido',
    'Sortudo',
    'Furioso',
    'Cósmico',
    'Sábio',
    'Caótico',
    'Otimista',
  ],
};

const female = {
  subs: [
    'Capivara',
    'Raposa',
    'Lhama',
    'Lua',
    'Estrela',
    'Lenda',
    'Fada',
    'Coruja',
    'Formiga',
    'Mandioca',
    'Coxinha',
    'Flor',
    'Internet',
    'Gambiarra',
    'Astronauta',
    'Fã',
    'Aventureira',
    'Elfa',
    'Onça',
    'Arara',
    'Desenvolvedora',
    'Pessoa',
    'Expectadora',
    'Lontra',
    'Sardinha',
  ],
  ads: [
    'Bagunceira',
    'Misteriosa',
    'Cansada',
    'Pagodeira',
    'Baiana',
    'Carioca',
    'Paulista',
    'Quebrada',
    'Suprema',
    'Lendária',
    'Aleatória',
    'Sonhadora',
    'Faminta',
    'Curiosa',
    'Veloz',
    'Zen',
    'Hacker',
    'Invisível',
    'Divertida',
    'Sortuda',
    'Furiosa',
    'Cósmica',
    'Sábia',
    'Caótica',
    'Otimista',
  ],
};

export function generateRandomNickname(): string {
  const isFemale = Math.random() > 0.5;

  const source = isFemale ? female : male;

  const sub = source.subs[Math.floor(Math.random() * source.subs.length)];
  const ad = source.ads[Math.floor(Math.random() * source.ads.length)];

  return `${sub} ${ad}`;
}
