const projects = [
  {
    id: '1a2b3c-4d5e-6f7g8h9i0j1k',
    name: 'Nyan Catrometer',
    imgThumb: 'https://github.com/user-attachments/assets/eea94a61-277a-4eb1-9ffc-6296f1d1d37d',
    img: 'https://user-images.githubusercontent.com/85768828/156932072-b2657998-4515-4fbf-ad20-d660108808a9.gif',
    description:
      'A simple and fun timer app that features the iconic Nyan Cat. It allows users to set timers and enjoy the Nyan Cat animation while waiting.',
    deployed: true,
    techStacks: ['React', 'HTML', 'CSS', 'JavaScript'],
    comments: 5,
    likes: 7,
    commits: 17,
    url: 'https://warywise.github.io/nyan-cronometer/',
    gitRepo: 'https://github.com/Warywise/nyan-cronometer',
  },
  {
    id: '2b3c4d-5e6f-7g8h9i0j1k2l',
    name: 'ChoqueFlix',
    imgThumb: 'https://github.com/user-attachments/assets/841b7e0d-c075-49b4-8b1a-8c365c3da936',
    img: 'https://user-images.githubusercontent.com/85768828/156933617-eba902b5-2534-4e71-b74e-34c4f903fbc7.gif',
    description:
      'Um site baseado no design da Netflix com o tema do canal do youtube Choque de Cultura. Dispõe de diversas informações de filmes obtidos através da API do TMDB.',
    deployed: false,
    techStacks: ['Vanilla', 'HTML', 'CSS', 'JavaScript', 'JQuery'],
    comments: 18,
    likes: 6,
    commits: 246,
    url: 'https://warywise.github.io/choqueflix',
    gitRepo: 'https://github.com/Warywise/choqueflix',
  },
  {
    id: '1a2b3c-4d5-6f7g8h9i0j1k',
    name: 'Three Meals',
    imgThumb: 'https://github.com/user-attachments/assets/aad2aaa2-e504-4f0f-9003-1079541362e5',
    img: 'https://github.com/user-attachments/assets/83c3dae4-e5b0-4206-a77f-f0985db30496',
    description:
      'App de Receitas com finalidade de trazer um grande acervo de receitas de comidas e bebidas de diversas localidades do mundo. App com melhor experiência em dispositivos mobile.',
    deployed: true,
    techStacks: ['React', 'HTML', 'CSS', 'JavaScript'],
    comments: 3,
    likes: 5,
    commits: 17,
    url: 'https://sant-recipes-app.vercel.app/',
    gitRepo: 'https://github.com/Warywise/sant-recipes-app',
  },
  {
    id: '2b3c4d-5e6-7g8h9i0j1k2l',
    name: 'ChoqueFlix',
    imgThumb: 'https://github.com/user-attachments/assets/841b7e0d-c075-49b4-8b1a-8c365c3da936',
    img: 'https://user-images.githubusercontent.com/85768828/156933617-eba902b5-2534-4e71-b74e-34c4f903fbc7.gif',
    description:
      'Um site baseado no design da Netflix com o tema do canal do youtube Choque de Cultura. Dispõe de diversas informações de filmes obtidos através da API do TMDB.',
    deployed: false,
    techStacks: ['Vanilla', 'HTML', 'CSS', 'JavaScript', 'JQuery'],
    comments: 14,
    likes: 9,
    commits: 246,
    url: 'https://warywise.github.io/choqueflix',
    gitRepo: 'https://github.com/Warywise/choqueflix',
  },
  {
    id: '1ab3c-4d5e-6f7g8h9i0j1k',
    name: 'Nyan Catrometer',
    imgThumb: 'https://github.com/user-attachments/assets/eea94a61-277a-4eb1-9ffc-6296f1d1d37d',
    img: 'https://user-images.githubusercontent.com/85768828/156932072-b2657998-4515-4fbf-ad20-d660108808a9.gif',
    description:
      'A simple and fun timer app that features the iconic Nyan Cat. It allows users to set timers and enjoy the Nyan Cat animation while waiting.',
    deployed: false,
    techStacks: ['React', 'HTML', 'CSS', 'JavaScript'],
    comments: 27,
    likes: 14,
    commits: 17,
    url: 'https://warywise.github.io/nyan-cronometer/',
    gitRepo: 'https://github.com/Warywise/nyan-cronometer',
  },
  {
    id: '2bc4d-5e6f-7g8h9i0j1k2l',
    name: 'Three Meals',
    imgThumb: 'https://github.com/user-attachments/assets/aad2aaa2-e504-4f0f-9003-1079541362e5',
    img: 'https://github.com/user-attachments/assets/83c3dae4-e5b0-4206-a77f-f0985db30496',
    description:
      'App de Receitas com finalidade de trazer um grande acervo de receitas de comidas e bebidas de diversas localidades do mundo. App com melhor experiência em dispositivos mobile.',
    deployed: true,
    techStacks: ['React', 'HTML', 'CSS', 'JavaScript'],
    comments: 34,
    likes: 9,
    commits: 246,
    url: 'https://sant-recipes-app.vercel.app/',
    gitRepo: 'https://github.com/Warywise/sant-recipes-app',
  },
];

export default projects;
